version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/google/mtail
    steps:
      - checkout
      - run: make vm/parser.go
      - run: make install_coverage_deps
      - run: time make testrace
      - run: make coverage
      - run: goveralls -coverprofile=gover.coverprofile
      - run: make bench
